spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weddingplanner
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      filter-order: 3

---
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weddingplanner
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update